export const httpBodyAndQueriesConsts = {
  query_page: "page",
  query_rowslimit: "rowslimit",
  body_logWasCreated: "logWasCreated",
  body_logWasUploadedToApi: "logWasUploadedToApi",
  body_sendFromSource: "sendFromSource",
  body_sendFromSystem: "sendFromSystem",
  body_sendFromCustomer: "sendFromCustomer",
  body_sendFromUser: "sendFromUser",
  body_shortDescription: "shortDescription",
  body_longDescription: "longDescription",
  body_isShowingAnError: "isShowingAnError",
  body_errorCode: "errorCode",
  body_errorDescription: "errorDescription",
};
