export const systemlogsDBModel = {
  tab_tableName: "systemlogs",
  col_id: "id",
  col_logWasCreated: "logWasCreated",
  col_logWasUploadedToApi: "logWasUploadedToApi",
  col_sendFromSource: "sendFromSource",
  col_sendFromSystem: "sendFromSystem",
  col_sendFromCustomer: "sendFromCustomer",
  col_sendFromUser: "sendFromUser",
  col_shortDescription: "shortDescription",
  col_longDescription: "longDescription",
  col_isShowingAnError: "isShowingAnError",
  col_errorCode: "errorCode",
  col_errorDescription: "errorDescription",
  col_comment: "comment",
};
